spring.application.name=springboot_learning
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journal_db
#spring.data.mongodb.username=myjournlkauser
#spring.data.mongodb.password=mypassword
